# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        dotnet publish CSharpActionsTest/CSharpActionsTest.csproj -c Release -o win-x64 --nologo --self-contained -r win-x64
        dotnet publish CSharpActionsTest/CSharpActionsTest.csproj -c Release -o linux-x64 --nologo --self-contained -r linux-x64
        dotnet publish CSharpActionsTest/CSharpActionsTest.csproj -c Release -o osx-x64 --nologo --self-contained -r osx-x64
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: Test-win-x64
        path: /home/runner/work/CSharpActionsTest/CSharpActionsTest/win-x64/
    - name: Upload Linux build
      uses: actions/upload-artifact@v4
      with:
        name: Test-linux-x64
        path: /home/runner/work/CSharpActionsTest/CSharpActionsTest/linux-x64/
    - name: Upload OSX build
      uses: actions/upload-artifact@v4
      with:
        name: Test-osx-x64
        path: /home/runner/work/CSharpActionsTest/CSharpActionsTest/osx-x64/
